#!/usr/bin/perl
use strict;
use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Statistics::Lite qw(mean);
use Statistics::Basic qw(:all); #cpanm Statistics::Basic で導入しておく必要あり
#version history=============================================================================
#v0.1 contig両末端の末端2000bpからprimer作成、リピートマスクのdefaultは16
#v0.2 カバレッジ中央値をとるカラムを間違えていたので修正(column9:Median_foldから取る)。top10lengthからのみ集めるように修正。末端抽出サイズを選択するフラグ追加。
#0.3 カバレッジ中央値を10000bp以上のcontigからとり、それらからSDx3（99%正確）を計算し、ばらつきを求める。SDx3範囲内のcontigのみprimerを設計する。SDを使うため、カバレッジ中央値はカバレッジ平均値に変更。
#0.4 primerがないcontigでprimer名がずれる問題を修正。$minsize以上で異常なカバレッジのcontig名を別出力するよう修正
#0.5 平均カバレッジ、残す最大カバレッジ、最小カバレッジのオプション指定に対応
#0.6 blobtoolsでのplotに対応(blobtools、numpy、matplotlib、samtools、sminimap2、diamond,bwaをインストール)
#0.61 diamond検索クエリ配列の最小サイズフラグを設定。それ以下は検索しない
#0.63 taxonkitサブルーチン&taxidを導入。contigにクエリ情報を追加（blobtools実行時のみ）。taxonkitはdatabaseファイルもいるので準備を忘れないこと(cp names.dmp nodes.dmp $HOME/.taxonkit/)
#0.7 taxidチェックをindex検索と並列化で高速化
#0.8 bacteria assemblyに修正
#dependency==================================================================================
##bbmap(merge pair reads)
##blobtools(contig plot)
##bwa(mapping for blobtools)
##unicycler(genome assembly)
##pilon(polish)
##elprep(polish)
##sambamba(chimera assembly check)
##nanoplot (ONT quality check)
##nanoplot and Nanofilt (ONT quality check)
#parameters===================================================================================
my $contig = "";
my $mask = "masked.fa";
my $fastq1 = "";
my $fastq2 = "";
my $nanopore = "";
my $minsize = "2000";
my $thread = "20";
my $end = "1000";
my $select1 = "55,81,101,115,127";
my $meancov = "";
my $maximumcov = "";
my $minimumcov = "";
my $diamonddb = "";
my $pilon = "";
my $evalue = "1e-100";
my $taxiddb = "/root/uniprot_ref_proteomes.taxids";
my $contiglimit = 1000;
my $mapper = "minimap2";
my $primerrun = "no";
my $div = "3";
my $nodeDB = "";
my $bobtoolswitch = "0";

#option=======================================================================================
GetOptions('w=s' => \$bobtoolswitch, 'b=s' => \$nodeDB, 'p=s' => \$pilon, 'n=s' => \$nanopore,'1=s' => \$fastq1,'2=s' => \$fastq2,'l=i' => \$end,'mc=i' => \$meancov,'minc=i' => \$minimumcov,'maxc=i' => \$maximumcov,'d=s' => \$diamonddb,'e=s' => \$evalue,'taxdb=s' => \$taxiddb,'t=i' => \$thread,'cl=i' => \$contiglimit,'map=s' => \$mapper,'primer=s' => \$primerrun,'k=i' => \$div);
#title========================================================================================
print "=============================================================================\n";
print "#genome quest version0.37\t2025 01 16\n";
print "Contact\: Kazuma Uesaka \<kazumaxneo\@gmail.com\>\n\n";
print "Usage\: genome quest \[options\]\n";
print "Options\:\n";
print "\t-f\tassembly fasta\n";
print "\t-1\tpaired read 1\n";
print "\t-2\tpaired read 2\n";
print "\t-n\tONT long read\n";
print "\t-p\tpath of pilon.jar\n";
print "\t-b\tnode DB\n";
print "\t-t\tthread number \(default 32\)\n";
print "\t-k\t parallel thread number \(default 3\)\n";
print "\t-cl\tminimum contig length for diamond blastx search \(default 500\)\n";
print "\t-e\tevalue threshould for blastx uisng diamond \(default 1e-100\)\n";
print "\t-d\tpath of diamond protein database for blobtools plotting \(default \-\)\n";
print "\t-taxdb\tNCBI taxonomy ID database file\(default \/root\/uniprot_ref_proteomes\.taxids\)\n";
print "\t-w On Off Blobplot figure creation \(default 0\, ON is 1\) \n\n\n";
print "ex\. run genome assembly \:\tgenome_quest \-1 short_R1.fq.gz \-2 short_R2.fq.gz \-n ONT.fq.gz \-p /usr/local/bin/pilon-1.24.jar \-b /nodeDB/nodesDB.txt \-d /nodeDB/uniprot_ref_proteomes.diamond.dmnd \n\n";
print "=============================================================================\n";

#error
die "\npaired-end fastq files are required !\n\n\n" if($fastq1 eq "");
die "\npaired-end fastq files are required !\n\n\n" if($fastq2 eq "");

system("mkdir -p 1_raw_reads 2_QT_reads/short_read_quality_check 2_QT_reads/raw_long_read_quality_check 2_QT_reads/QT_long_read_quality_check 3_assembly_results/Flye 3_assembly_results/Flye40kb 3_assembly_results/Flye50kb 3_assembly_results/Unicycler 4_contamineation_check");
system("mkdir -p 5_re-polish/Unicycler 5_re-polish/Flye 5_re-polish/Flye40kb 5_re-polish/Flye50kb");
system("mkdir -p detail/2_QT_reads detail/2_QT_reads/QT_long_read_quality_check detail/2_QT_reads/raw_long_read_quality_check detail/3_assembly_results/Flye detail/3_assembly_results/Unicycler detail/4_contamineation_check detail/5_polish/Flye detail/5_polish/Unicycler  detail/5_polish/Flye40kb  detail/5_polish/Flye50kb");

my $i = 1;my @cov = "";my @size = "";my @gc = "";my $total = 0;my @medi = "";my $meanvalue = 0;my $standarddivision = 0;my $sd = 0;

#subroutine_part1==============================================================================
&qc if($contig eq "");
&assembly if($contig eq "");
&polish if($contig eq "");
$contig = "contigs.fasta" if($contig eq "");
&blastx unless($diamonddb eq "");
&blobtool unless($diamonddb eq "");

system("sed \-e \"s\/_pilon\/\/g\" 5_re-polish/Unicycler/manual_polished.fasta > 1");
system("sed -e \"s/>1/>chr/g\" 1 > 2 ");
system("sed -e \"s/>2/>plasmid1/g\" 2 > 3 ");
system("sed -e \"s/>3/>plasmid2/g\" 3 > 4 ");
system("sed -e \"s/>4/>plasmid3/g\" 4 > 5 ");
system("sed -e \"s/>5/>plasmid4/g\" 5 > 6 ");
system("sed -e \"s/>6/>plasmid5/g\" 6 > 7 ");
system("sed -e \"s/>7/>plasmid6/g\" 7 > 8 ");
system("sed -e \"s/>8/>plasmid7/g\" 8 > 9 ");
system("mv 9 5_re-polish/Unicycler/manual_polished.fasta");
system("rm 1 2 3 4 5 6 7 8 ");

system("sed \-e \"s\/_pilon\/\/g\" 5_re-polish/Flye/manual_polished.fasta > 1");
system("sed -e \"s/>contig_1/>chr/g\" 1 > 2 ");
system("sed -e \"s/>contig_2/>plasmid1/g\" 2 > 3 ");
system("sed -e \"s/>contig_3/>plasmid2/g\" 3 > 4 ");
system("sed -e \"s/>contig_4/>plasmid3/g\" 4 > 5 ");
system("sed -e \"s/>contig_5/>plasmid4/g\" 5 > 6 ");
system("sed -e \"s/>contig_6/>plasmid5/g\" 6 > 7 ");
system("sed -e \"s/>contig_7/>plasmid6/g\" 7 > 8 ");
system("sed -e \"s/>contig_8/>plasmid7/g\" 8 > 9 ");
system("mv 9 5_re-polish/Flye/manual_polished.fasta");
system("rm 1 2 3 4 5 6 7 8 ");

system("sed \-e \"s\/_pilon\/\/g\" 5_re-polish/Flye40kb/manual_polished.fasta > 1");
system("sed -e \"s/>contig_1/>chr/g\" 1 > 2 ");
system("sed -e \"s/>contig_2/>plasmid1/g\" 2 > 3 ");
system("sed -e \"s/>contig_3/>plasmid2/g\" 3 > 4 ");
system("sed -e \"s/>contig_4/>plasmid3/g\" 4 > 5 ");
system("sed -e \"s/>contig_5/>plasmid4/g\" 5 > 6 ");
system("sed -e \"s/>contig_6/>plasmid5/g\" 6 > 7 ");
system("sed -e \"s/>contig_7/>plasmid6/g\" 7 > 8 ");
system("sed -e \"s/>contig_8/>plasmid7/g\" 8 > 9 ");
system("mv 9 5_re-polish/Flye40kb/manual_polished.fasta");
system("rm 1 2 3 4 5 6 7 8 ");

system("sed \-e \"s\/_pilon\/\/g\" 5_re-polish/Flye50kb/manual_polished.fasta > 1");
system("sed -e \"s/>contig_1/>chr/g\" 1 > 2 ");
system("sed -e \"s/>contig_2/>plasmid1/g\" 2 > 3 ");
system("sed -e \"s/>contig_3/>plasmid2/g\" 3 > 4 ");
system("sed -e \"s/>contig_4/>plasmid3/g\" 4 > 5 ");
system("sed -e \"s/>contig_5/>plasmid4/g\" 5 > 6 ");
system("sed -e \"s/>contig_6/>plasmid5/g\" 6 > 7 ");
system("sed -e \"s/>contig_7/>plasmid6/g\" 7 > 8 ");
system("sed -e \"s/>contig_8/>plasmid7/g\" 8 > 9 ");
system("mv 9 5_re-polish/Flye50kb/manual_polished.fasta");
system("rm 1 2 3 4 5 6 7 8 ");

#Unicycler
system("bbmap.sh ref=5_re-polish/Unicycler/manual_polished.fasta nodisk in1=$fastq1 in2=$fastq2 covstats=5_re-polish/Unicycler/mapping.stats");
system("rm *html split mapped.bam.cov merged.fq quality_trimmed_1.fq.gz quality_trimmed_2.fq.gz nanopore_trimmed.fq.gz blastx-out");
system("mv diamond-out detail/4_contamineation_check/");
system("mv contigs.fasta detail/3_assembly_results/Unicycler");
system("mv 4_contamineation_check/blobDB.json detail/4_contamineation_check");
system("rm -rf 4_contamineation_check/blobtools");
system("mv 5_re-polish/Unicycler/pilon* detail/5_polish/Unicycler");
system("mv 5_re-polish/Unicycler/temp/reference.fa 5_re-polish/Unicycler/");
system("mv 5_re-polish/Unicycler/temp/reference.fa.fai 5_re-polish/Unicycler/");
system("mv 5_re-polish/Unicycler/temp/F_sorted.bam* 5_re-polish/Unicycler/");
system("mv 5_re-polish/Unicycler/temp/R_sorted.bam* 5_re-polish/Unicycler/");
system("rm -rf 5_re-polish/Unicycler/temp");
system("rm 5_re-polish/Unicycler/assembly.elfasta 5_re-polish/Unicycler/assembly.fasta 5_re-polish/Unicycler/pilon.elfasta");
system("rm -rf detail/3_assembly_results/Unicycler/blast detail/3_assembly_results/Unicycler/pilon_polish detail/5_polish/Unicycler/pilon.elfasta detail/4_contamineation_check/diamond-out 20kb.fq 40kb.fq 50kb.fq log");

#Flye
system("bbmap.sh ref=5_re-polish/Flye/manual_polished.fasta nodisk in1=$fastq1 in2=$fastq2 covstats=5_re-polish/Flye/mapping.stats");
system("mv 5_re-polish/Flye/pilon* detail/5_polish/Flye");
system("mv 5_re-polish/Flye/temp/reference.fa 5_re-polish/Flye/");
system("mv 5_re-polish/Flye/temp/reference.fa.fai 5_re-polish/Flye/");
system("mv 5_re-polish/Flye/temp/F_sorted.bam* 5_re-polish/Flye/");
system("mv 5_re-polish/Flye/temp/R_sorted.bam* 5_re-polish/Flye/");
system("rm -rf 5_re-polish/Flye/temp");
system("rm 1 2 3 4 5 6 7 8 5_re-polish/Flye/assembly.elfasta 5_re-polish/Flye/assembly.fasta 5_re-polish/Flye/pilon.elfasta");
system("rm -rf diamond-out detail/3_assembly_results/Flye/blast detail/3_assembly_results/Flye/pilon_polish detail/5_polish/Flye/pilon.elfasta detail/4_contamineation_check/diamond-out temp2");

#Flye40kb
system("bbmap.sh ref=5_re-polish/Flye40kb/manual_polished.fasta nodisk in1=$fastq1 in2=$fastq2 covstats=5_re-polish/Flye40kb/mapping.stats");
system("mv 5_re-polish/Flye40kb/pilon* detail/5_polish/Flye40kb");
system("mv 5_re-polish/Flye40kb/temp/reference.fa 5_re-polish/Flye40kb/");
system("mv 5_re-polish/Flye40kb/temp/reference.fa.fai 5_re-polish/Flye40kb/");
system("mv 5_re-polish/Flye40kb/temp/F_sorted.bam* 5_re-polish/Flye40kb/");
system("mv 5_re-polish/Flye40kb/temp/R_sorted.bam* 5_re-polish/Flye40kb/");
system("rm -rf 5_re-polish/Flye40kb/temp");
system("rm 1 2 3 4 5 6 7 8 5_re-polish/Flye40kb/assembly.elfasta 5_re-polish/Flye40kb/assembly.fasta 5_re-polish/Flye40kb/pilon.elfasta");
system("rm -rf diamond-out detail/3_assembly_results/Flye/blast detail/3_assembly_results/Flye/pilon_polish detail/5_polish/Flye/pilon.elfasta detail/4_contamineation_check/diamond-out temp2");

#Flye50kb
system("bbmap.sh ref=5_re-polish/Flye50kb/manual_polished.fasta nodisk in1=$fastq1 in2=$fastq2 covstats=5_re-polish/Flye50kb/mapping.stats");
system("mv 5_re-polish/Flye50kb/pilon* detail/5_polish/Flye50kb");
system("mv 5_re-polish/Flye50kb/temp/reference.fa 5_re-polish/Flye50kb/");
system("mv 5_re-polish/Flye50kb/temp/reference.fa.fai 5_re-polish/Flye50kb/");
system("mv 5_re-polish/Flye50kb/temp/F_sorted.bam* 5_re-polish/Flye50kb/");
system("mv 5_re-polish/Flye50kb/temp/R_sorted.bam* 5_re-polish/Flye50kb/");
system("rm -rf 5_re-polish/Flye50kb/temp");
system("rm 1 2 3 4 5 6 7 8 5_re-polish/Flye50kb/assembly.elfasta 5_re-polish/Flye50kb/assembly.fasta 5_re-polish/Flye50kb/pilon.elfasta");
system("rm -rf diamond-out detail/3_assembly_results/Flye/blast detail/3_assembly_results/Flye/pilon_polish detail/5_polish/Flye/pilon.elfasta detail/4_contamineation_check/diamond-out temp2");
system("seqkit stats -T -a 5_re-polish/*/*fasta > 5_re-polish/stats.txt");
system("seqkit stats -T -a 3_assembly_results//*/*fasta > 3_assembly_results/stats.txt");
system("chmod a+rw -R * ");
exit;

#==================================================================================================================
#===============================================subroutine=========================================================
sub qc {
	system("echo $fastq1 $fastq2 $nanopore");
	system("seqkit stats -T $fastq1 $fastq2 $nanopore > 1_raw_reads/raw_stats.txt");
	system("NanoPlot --fastq $nanopore --loglength -t 12 -o detail/2_QT_reads/raw_long_read_quality_check");
	system("fastp -i $fastq1 -I $fastq2 -3 -o 2_QT_reads/quality_trimmed_1.fq.gz -O 2_QT_reads/quality_trimmed_2.fq.gz -h 2_QT_reads/short_read_quality_check/report.html -j 2_QT_reads/short_read_quality_check/report.json -q 30 -n 20 -t 1 -T 1 -f 1 -F 1 -w 16");
	system("filtlong -1 2_QT_reads/quality_trimmed_1.fq.gz -2 2_QT_reads/quality_trimmed_2.fq.gz --min_length 3000 --keep_percent 80 --target_bases 500000000 --trim --split 500 $nanopore > 2_QT_reads/nanopore_trimmed.fq ");
	system("pigz -p $thread 2_QT_reads/nanopore_trimmed.fq");
	system("NanoPlot --fastq 2_QT_reads/nanopore_trimmed.fq.gz --loglength -t 12 -o detail/2_QT_reads/QT_long_read_quality_check");
	system("seqkit stats -T 2_QT_reads/quality_trimmed* 2_QT_reads/nanopore_trimmed.fq.gz > 2_QT_reads/QT_stats.txt");
	system("seqkit seq -m 20000 2_QT_reads/nanopore_trimmed.fq.gz > 20kb.fq");
	system("seqkit seq -m 40000 2_QT_reads/nanopore_trimmed.fq.gz > 40kb.fq");
	system("seqkit seq -m 50000 2_QT_reads/nanopore_trimmed.fq.gz > 50kb.fq");
	system("mv detail/2_QT_reads/raw_long_read_quality_check/NanoPlot-report.html 2_QT_reads/raw_long_read_quality_check/");
	system("mv detail/2_QT_reads/QT_long_read_quality_check/NanoPlot-report.html 2_QT_reads/QT_long_read_quality_check/");
	system("sleep 1s");
	system("bbmerge.sh in1=2_QT_reads/quality_trimmed_1.fq.gz in2=2_QT_reads/quality_trimmed_2.fq.gz out=merged.fq &");
}

#==================================================================================================================
sub assembly {
	system("unicycler -t $thread -o detail/3_assembly_results/Unicycler/ -1 2_QT_reads/quality_trimmed_1.fq.gz -2 2_QT_reads/quality_trimmed_2.fq.gz -l 2_QT_reads/nanopore_trimmed.fq.gz --keep 3");
	system("flye --nano-raw 20kb.fq --out-dir detail/3_assembly_results/Flye/ --threads $thread");
	system("flye --nano-raw 50kb.fq --out-dir detail/3_assembly_results/Flye50kb/ --threads $thread");
	system("flye --nano-raw 40kb.fq --out-dir detail/3_assembly_results/Flye40kb/ --threads $thread");
	#system("cp detail/3_assembly_results/Unicycler/spades_assembly/contigs.fasta .");
	#system("mv diamond-out split blastx-out mapped.bam.cov temp2/");
	system("rm -rf detail/3_assembly_results/Unicycler/simple_bridging detail/3_assembly_results/Unicycler/read_alignment detail/3_assembly_results/Unicycler/miniasm_assembly detail/3_assembly_results/Unicycler/spades_assembly");
	system("mv detail/3_assembly_results/Unicycler/assembly.fasta 3_assembly_results/Unicycler/");
	system("mv detail/3_assembly_results/Flye/assembly.fasta 3_assembly_results/Flye/");
	system("mv detail/3_assembly_results/Flye40kb/assembly.fasta 3_assembly_results/Flye40kb/");
	system("mv detail/3_assembly_results/Flye50kb/assembly.fasta 3_assembly_results/Flye50kb/");
	system("Bandage image detail/3_assembly_results/Unicycler/assembly.gfa 3_assembly_results/Unicycler/Figure2A.png");
	system("Bandage image detail/3_assembly_results/Flye/assembly_graph.gfa 3_assembly_results/Flye/Figure2B.png");
	system("Bandage image detail/3_assembly_results/Flye40kb/assembly_graph.gfa 3_assembly_results/Flye40kb/Figure2C.png");
	system("Bandage image detail/3_assembly_results/Flye50kb/assembly_graph.gfa 3_assembly_results/Flye50kb/Figure2D.png");
}

#==================================================================================================================
sub polish {
	system("cp 2_QT_reads/*fq.gz . ");
	#$R1 = "quality_trimmed_1.fq.gz";
	#$R2 = "quality_trimmed_2.fq.gz";
	#$long = "nanopore_trimmed.fq.gz";
	system("cp 3_assembly_results/Unicycler/assembly.fasta 5_re-polish/Unicycler/ ");
	system("cp 3_assembly_results/Flye/assembly.fasta 5_re-polish/Flye/ ");
	system("cp 3_assembly_results/Flye/assembly.fasta 5_re-polish/Flye40kb/ ");
	system("cp 3_assembly_results/Flye/assembly.fasta 5_re-polish/Flye50kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Unicycler/assembly.fasta 5_re-polish/Unicycler/assembly.elfasta");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/assembly.fasta 5_re-polish/Flye/assembly.elfasta");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/assembly.fasta 5_re-polish/Flye40kb/assembly.elfasta");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/assembly.fasta 5_re-polish/Flye50kb/assembly.elfasta");
	system("bbmerge.sh in1=$fastq1 in2=$fastq2 out=merged.fq ");
	#$merge = "merged.fq";
	
	#Unicycler
	system("minimap2 -ax sr -t $thread 5_re-polish/Unicycler/assembly.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Unicycler/short1.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict 1> log");
	system("samtools index -@ 8 5_re-polish/Unicycler/short1.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Unicycler/assembly.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Unicycler/long1.bam && samtools index -@ 8 5_re-polish/Unicycler/long1.bam ");
	system("java -Xmx40G -jar $pilon --genome 5_re-polish/Unicycler/assembly.fasta --frags 5_re-polish/Unicycler/short1.bam --nanopore 5_re-polish/Unicycler/long1.bam --changes --threads $thread --outdir 5_re-polish/Unicycler/pilon_output_dir1 1> log && cp 5_re-polish/Unicycler/pilon_output_dir1/pilon.fasta 5_re-polish/Unicycler/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Unicycler/pilon.fasta 5_re-polish/Unicycler/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Unicycler/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Unicycler/short2.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict 1> log");
	system("samtools index -@ 8 5_re-polish/Unicycler/short2.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Unicycler/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Unicycler/long2.bam && samtools index -@ 8 5_re-polish/Unicycler/long2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Unicycler/pilon.fasta --frags 5_re-polish/Unicycler/short2.bam --nanopore 5_re-polish/Unicycler/long2.bam --changes --threads $thread --outdir 5_re-polish/Unicycler/pilon_output_dir2 1> log && cp 5_re-polish/Unicycler/pilon_output_dir2/pilon.fasta 5_re-polish/Unicycler/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Unicycler/pilon.fasta 5_re-polish/Unicycler/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Unicycler/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Unicycler/short3.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict 1> log");
	system("samtools index -@ 8 5_re-polish/Unicycler/short3.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Unicycler/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Unicycler/long3.bam && samtools index -@ 8 5_re-polish/Unicycler/long3.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Unicycler/pilon.fasta --frags 5_re-polish/Unicycler/short3.bam --nanopore 5_re-polish/Unicycler/long3.bam --changes --threads $thread --outdir 5_re-polish/Unicycler/pilon_output_dir3 1> log && cp 5_re-polish/Unicycler/pilon_output_dir3/pilon.fasta 5_re-polish/Unicycler/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Unicycler/pilon.fasta 5_re-polish/Unicycler/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Unicycler/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Unicycler/short4.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict 1> log");
	system("samtools index -@ 8 5_re-polish/Unicycler/short4.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Unicycler/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Unicycler/merge1.bam && samtools index -@ 8 5_re-polish/Unicycler/merge1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Unicycler/pilon.fasta --frags 5_re-polish/Unicycler/short4.bam --pacbio 5_re-polish/Unicycler/merge1.bam --changes --threads $thread --outdir 5_re-polish/Unicycler/pilon_output_dir4 1> log && cp 5_re-polish/Unicycler/pilon_output_dir4/pilon.fasta 5_re-polish/Unicycler/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Unicycler/pilon.fasta 5_re-polish/Unicycler/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Unicycler/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Unicycler/short5.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict 1> log");
	system("samtools index -@ 8 5_re-polish/Unicycler/short5.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Unicycler/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Unicycler/merge2.bam && samtools index -@ 8 5_re-polish/Unicycler/merge2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Unicycler/pilon.fasta --frags 5_re-polish/Unicycler/short5.bam --pacbio 5_re-polish/Unicycler/merge2.bam --changes --threads $thread --outdir 5_re-polish/Unicycler/pilon_output_dir5 1> log && cp 5_re-polish/Unicycler/pilon_output_dir5/pilon.fasta 5_re-polish/Unicycler/ ");
	system("samtools faidx 5_re-polish/Unicycler/pilon.fasta ");
	system("SV-Quest1.pl -f 5_re-polish/Unicycler/pilon.fasta -1 $fastq1 -2 $fastq2 ");
	system("seqkit seq -m 5000 2_QT_reads/nanopore_trimmed.fq.gz |gzip - > ONT_5000-50000_x100.fg.gz");
	system("minimap2 -ax map-ont -t $thread temp/reference.fa ONT_5000-50000_x100.fg.gz 2> /dev/null |samtools sort -@ 8 - > ONT.bam");
	system("samtools view -@ 2 -bSq 10 ONT.bam > ONT_filtered.bam && samtools index -@ 4 ONT_filtered.bam");
	system("mkdir work_dir && cuteSV -t $thread -s 20 -r 1000 -l 10 ONT_filtered.bam temp/reference.fa cuteSV.vcf work_dir");
	system("rm 5_re-polish/Unicycler/*bam* 5_re-polish/Unicycler/*fai 5_re-polish/Unicycler/*pilon*html 5_re-polish/Unicycler/*.elfasta 5_re-polish/Unicycler/assembly.fasta ONT.bam");
	system("mv 5_re-polish/Unicycler/pilon.fasta 5_re-polish/Unicycler/manual_polished.fasta ");
	system("mv temp ONT_filtered.bam* summary/InDel.txt cuteSV.vcf 5_re-polish/Unicycler");
	system("rm -rf temp2/ summary/ work_dir");

	#Flye
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye/assembly.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye/short1.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye/short1.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye/assembly.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye/long1.bam && samtools index -@ 8 5_re-polish/Flye/long1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye/assembly.fasta --frags 5_re-polish/Flye/short1.bam --nanopore 5_re-polish/Flye/long1.bam --changes --threads $thread --outdir 5_re-polish/Flye/pilon_output_dir1 1> log && cp 5_re-polish/Flye/pilon_output_dir1/pilon.fasta 5_re-polish/Flye/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/pilon.fasta 5_re-polish/Flye/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye/short2.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye/short2.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye/long2.bam && samtools index -@ 8 5_re-polish/Flye/long2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye/pilon.fasta --frags 5_re-polish/Flye/short2.bam --nanopore 5_re-polish/Flye/long2.bam --changes --threads $thread --outdir 5_re-polish/Flye/pilon_output_dir2 1> log && cp 5_re-polish/Flye/pilon_output_dir2/pilon.fasta 5_re-polish/Flye/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/pilon.fasta 5_re-polish/Flye/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye/short3.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye/short3.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye/long3.bam && samtools index -@ 8 5_re-polish/Flye/long3.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye/pilon.fasta --frags 5_re-polish/Flye/short3.bam --nanopore 5_re-polish/Flye/long3.bam --changes --threads $thread --outdir 5_re-polish/Flye/pilon_output_dir3 1> log && cp 5_re-polish/Flye/pilon_output_dir3/pilon.fasta 5_re-polish/Flye/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/pilon.fasta 5_re-polish/Flye/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye/short4.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye/short4.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Flye/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye/merge1.bam && samtools index -@ 8 5_re-polish/Flye/merge1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye/pilon.fasta --frags 5_re-polish/Flye/short4.bam --pacbio 5_re-polish/Flye/merge1.bam --changes --threads $thread --outdir 5_re-polish/Flye/pilon_output_dir4 1> log && cp 5_re-polish/Flye/pilon_output_dir4/pilon.fasta 5_re-polish/Flye/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye/pilon.fasta 5_re-polish/Flye/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye/short5.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye/short5.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Flye/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye/merge2.bam && samtools index -@ 8 5_re-polish/Flye/merge2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye/pilon.fasta --frags 5_re-polish/Flye/short5.bam --pacbio 5_re-polish/Flye/merge2.bam --changes --threads $thread --outdir 5_re-polish/Flye/pilon_output_dir5 1> log && cp 5_re-polish/Flye/pilon_output_dir5/pilon.fasta 5_re-polish/Flye/ ");
	system("samtools faidx 5_re-polish/Flye/pilon.fasta ");
	system("SV-Quest1.pl -f 5_re-polish/Flye/pilon.fasta -1 $fastq1 -2 $fastq2 ");
	system("minimap2 -ax map-ont -t $thread temp/reference.fa ONT_5000-50000_x100.fg.gz 2> /dev/null |samtools sort -@ 8 - > ONT.bam");
	system("samtools view -@ 2 -bSq 10 ONT.bam > ONT_filtered.bam && samtools index -@ 4 ONT_filtered.bam");
	system("mkdir work_dir && cuteSV -t $thread -s 20 -r 1000 -l 10 ONT_filtered.bam temp/reference.fa cuteSV.vcf work_dir");
	system("rm 5_re-polish/Flye/*bam* 5_re-polish/Flye/*fai 5_re-polish/Flye/*pilon*html 5_re-polish/Flye/*.elfasta 5_re-polish/Flye/assembly.fasta ONT.bam");
	system("mv 5_re-polish/Flye/pilon.fasta 5_re-polish/Flye/manual_polished.fasta ");
	system("mv temp ONT_filtered.bam* summary/InDel.txt cuteSV.vcf 5_re-polish/Flye");
	system("rm -rf temp2/ summary/ work_dir");
	
	#Flye 40kb reads
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye40kb/assembly.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye40kb/short1.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye40kb/short1.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye40kb/assembly.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye40kb/long1.bam && samtools index -@ 8 5_re-polish/Flye40kb/long1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye40kb/assembly.fasta --frags 5_re-polish/Flye40kb/short1.bam --nanopore 5_re-polish/Flye40kb/long1.bam --changes --threads $thread --outdir 5_re-polish/Flye40kb/pilon_output_dir1 1> log && cp 5_re-polish/Flye40kb/pilon_output_dir1/pilon.fasta 5_re-polish/Flye40kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye40kb/pilon.fasta 5_re-polish/Flye40kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye40kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye40kb/short2.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye40kb/short2.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye40kb/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye40kb/long2.bam && samtools index -@ 8 5_re-polish/Flye40kb/long2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye40kb/pilon.fasta --frags 5_re-polish/Flye40kb/short2.bam --nanopore 5_re-polish/Flye40kb/long2.bam --changes --threads $thread --outdir 5_re-polish/Flye40kb/pilon_output_dir2 1> log && cp 5_re-polish/Flye40kb/pilon_output_dir2/pilon.fasta 5_re-polish/Flye40kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye40kb/pilon.fasta 5_re-polish/Flye40kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye40kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye40kb/short3.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye40kb/short3.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye40kb/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye40kb/long3.bam && samtools index -@ 8 5_re-polish/Flye40kb/long3.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye40kb/pilon.fasta --frags 5_re-polish/Flye40kb/short3.bam --nanopore 5_re-polish/Flye40kb/long3.bam --changes --threads $thread --outdir 5_re-polish/Flye40kb/pilon_output_dir3 1> log && cp 5_re-polish/Flye40kb/pilon_output_dir3/pilon.fasta 5_re-polish/Flye40kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye40kb/pilon.fasta 5_re-polish/Flye40kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye40kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye40kb/short4.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye40kb/short4.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Flye40kb/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye40kb/merge1.bam && samtools index -@ 8 5_re-polish/Flye40kb/merge1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye40kb/pilon.fasta --frags 5_re-polish/Flye40kb/short4.bam --pacbio 5_re-polish/Flye40kb/merge1.bam --changes --threads $thread --outdir 5_re-polish/Flye40kb/pilon_output_dir4 1> log && cp 5_re-polish/Flye40kb/pilon_output_dir4/pilon.fasta 5_re-polish/Flye40kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye40kb/pilon.fasta 5_re-polish/Flye40kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye40kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye40kb/short5.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye40kb/short5.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Flye40kb/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye40kb/merge2.bam && samtools index -@ 8 5_re-polish/Flye40kb/merge2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye40kb/pilon.fasta --frags 5_re-polish/Flye40kb/short5.bam --pacbio 5_re-polish/Flye40kb/merge2.bam --changes --threads $thread --outdir 5_re-polish/Flye40kb/pilon_output_dir5 1> log && cp 5_re-polish/Flye40kb/pilon_output_dir5/pilon.fasta 5_re-polish/Flye40kb/ ");
	system("samtools faidx 5_re-polish/Flye40kb/pilon.fasta ");
	system("SV-Quest1.pl -f 5_re-polish/Flye40kb/pilon.fasta -1 $fastq1 -2 $fastq2 ");
	system("minimap2 -ax map-ont -t $thread temp/reference.fa ONT_5000-50000_x100.fg.gz 2> /dev/null |samtools sort -@ 8 - > ONT.bam");
	system("samtools view -@ 2 -bSq 10 ONT.bam > ONT_filtered.bam && samtools index -@ 4 ONT_filtered.bam");
	system("mkdir work_dir && cuteSV -t $thread -s 20 -r 1000 -l 10 ONT_filtered.bam temp/reference.fa cuteSV.vcf work_dir");
	system("rm 5_re-polish/Flye40kb/*bam* 5_re-polish/Flye40kb/*fai 5_re-polish/Flye40kb/*pilon*html 5_re-polish/Flye40kb/*.elfasta 5_re-polish/Flye40kb/assembly.fasta ONT.bam");
	system("mv 5_re-polish/Flye40kb/pilon.fasta 5_re-polish/Flye40kb/manual_polished.fasta ");
	system("mv temp ONT_filtered.bam* summary/InDel.txt cuteSV.vcf 5_re-polish/Flye40kb");
	system("rm -rf temp2/ summary/ work_dir");
	
	#Flye 50kb reads
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye50kb/assembly.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye50kb/short1.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye50kb/short1.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye50kb/assembly.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye50kb/long1.bam && samtools index -@ 8 5_re-polish/Flye50kb/long1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye50kb/assembly.fasta --frags 5_re-polish/Flye50kb/short1.bam --nanopore 5_re-polish/Flye50kb/long1.bam --changes --threads $thread --outdir 5_re-polish/Flye50kb/pilon_output_dir1 1> log && cp 5_re-polish/Flye50kb/pilon_output_dir1/pilon.fasta 5_re-polish/Flye50kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye50kb/pilon.fasta 5_re-polish/Flye50kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye50kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye50kb/short2.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye50kb/short2.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye50kb/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye50kb/long2.bam && samtools index -@ 8 5_re-polish/Flye50kb/long2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye50kb/pilon.fasta --frags 5_re-polish/Flye50kb/short2.bam --nanopore 5_re-polish/Flye50kb/long2.bam --changes --threads $thread --outdir 5_re-polish/Flye50kb/pilon_output_dir2 1> log && cp 5_re-polish/Flye50kb/pilon_output_dir2/pilon.fasta 5_re-polish/Flye50kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye50kb/pilon.fasta 5_re-polish/Flye50kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye50kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye50kb/short3.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye50kb/short3.bam");
	system("minimap2 -t $thread -ax map-ont 5_re-polish/Flye50kb/pilon.fasta 2_QT_reads/nanopore_trimmed.fq.gz 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye50kb/long3.bam && samtools index -@ 8 5_re-polish/Flye50kb/long3.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye50kb/pilon.fasta --frags 5_re-polish/Flye50kb/short3.bam --nanopore 5_re-polish/Flye50kb/long3.bam --changes --threads $thread --outdir 5_re-polish/Flye50kb/pilon_output_dir3 1> log && cp 5_re-polish/Flye50kb/pilon_output_dir3/pilon.fasta 5_re-polish/Flye50kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye50kb/pilon.fasta 5_re-polish/Flye50kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye50kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye50kb/short4.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye50kb/short4.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Flye50kb/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye50kb/merge1.bam && samtools index -@ 8 5_re-polish/Flye50kb/merge1.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye50kb/pilon.fasta --frags 5_re-polish/Flye50kb/short4.bam --pacbio 5_re-polish/Flye50kb/merge1.bam --changes --threads $thread --outdir 5_re-polish/Flye50kb/pilon_output_dir4 1> log && cp 5_re-polish/Flye50kb/pilon_output_dir4/pilon.fasta 5_re-polish/Flye50kb/ ");
	system("elprep fasta-to-elfasta 5_re-polish/Flye50kb/pilon.fasta 5_re-polish/Flye50kb/pilon.elfasta");
	
	system("minimap2 -ax sr -t $thread 5_re-polish/Flye50kb/pilon.fasta $fastq1 $fastq2 2> /dev/null | elprep filter /dev/stdin 5_re-polish/Flye50kb/short5.bam --mark-duplicates --remove-duplicates --filter-mapping-quality 0 --clean-sam --nr-of-threads $thread --sorting-order coordinate --filter-unmapped-reads-strict ");
	system("samtools index -@ 8 5_re-polish/Flye50kb/short5.bam");
	system("minimap2 -t $thread -ax sr 5_re-polish/Flye50kb/pilon.fasta merged.fq 2> /dev/null | samtools sort -@ 8 -O BAM - > 5_re-polish/Flye50kb/merge2.bam && samtools index -@ 8 5_re-polish/Flye50kb/merge2.bam ");
	system("java -Xmx60G -jar $pilon --genome 5_re-polish/Flye50kb/pilon.fasta --frags 5_re-polish/Flye50kb/short5.bam --pacbio 5_re-polish/Flye50kb/merge2.bam --changes --threads $thread --outdir 5_re-polish/Flye50kb/pilon_output_dir5 1> log && cp 5_re-polish/Flye50kb/pilon_output_dir5/pilon.fasta 5_re-polish/Flye50kb/ ");
	system("samtools faidx 5_re-polish/Flye50kb/pilon.fasta ");
	system("SV-Quest1.pl -f 5_re-polish/Flye50kb/pilon.fasta -1 $fastq1 -2 $fastq2 ");
	system("minimap2 -ax map-ont -t $thread temp/reference.fa ONT_5000-50000_x100.fg.gz 2> /dev/null |samtools sort -@ 8 - > ONT.bam");
	system("samtools view -@ 2 -bSq 10 ONT.bam > ONT_filtered.bam && samtools index -@ 4 ONT_filtered.bam");
	system("mkdir work_dir && cuteSV -t $thread -s 20 -r 1000 -l 10 ONT_filtered.bam temp/reference.fa cuteSV.vcf work_dir");
	system("rm 5_re-polish/Flye50kb/*bam* 5_re-polish/Flye50kb/*fai 5_re-polish/Flye50kb/*pilon*html 5_re-polish/Flye50kb/*.elfasta 5_re-polish/Flye50kb/assembly.fasta ONT.bam ONT_5000-50000_x100.fg.gz");
	system("mv 5_re-polish/Flye50kb/pilon.fasta 5_re-polish/Flye50kb/manual_polished.fasta ");
	system("mv temp ONT_filtered.bam* summary/InDel.txt cuteSV.vcf 5_re-polish/Flye50kb");
	system("rm -rf temp2/ summary/ work_dir");
}

#==================================================================================================================
sub blastx {
	#unipprotデータベースとproteome_taxidはユーザがダウンロードして準備する必要がある。
	die "\npaired-end fastq files are required !\n\n\n" if($fastq1 eq "");
	print "spades assembly with sshort reads\n";
	system("spades.py -1 2_QT_reads/quality_trimmed_1.fq.gz -2 2_QT_reads/quality_trimmed_2.fq.gz -t $thread --only-assembler -o spades -k 31 1> log");
	system("seqkit seq -m $contiglimit spades/contigs.fasta > seq");
	system("cp spades/contigs.fasta detail/4_contamineation_check/");
	#system("prodigal -i seq -a protein.faa 1> log 2> log");
	print "blastx to database using diamond\n";
	system("mkdir temp2");
	system("diamond blastx --fast --query seq --db $diamonddb --outfmt 6 --max-target-seqs 1 --evalue $evalue > diamond-out");
	system("rm -rf log protein.faa spades");
	system("wc -l diamond-out |cut -f 1 -d \" \" > split");
	open INPUT6, "<split" or die "cant open split file!\n";
	my $splitvalue = <INPUT6>;
	my $splitnumber = int($splitvalue / $div);
	system("split -l $splitnumber diamond-out temp2/Split_");
	print "tax check using parallel command\n";
	system("ls temp2/Split_* | parallel -j $div \'tax-check.pl -i {} -o {}output \' ");
	system("cat temp2/*output > blastx-out");
}
#==================================================================================================================
sub blobtool {
	print "blobtools coverage plot\n";
	system("mkdir blobtools");
	system("minimap2 -ax sr -t $thread seq 2_QT_reads/quality_trimmed_1.fq.gz 2_QT_reads/quality_trimmed_2.fq.gz | samtools sort -O BAM -@ 8 - > blobtools/mapped.bam");
	system("samtools index -@ 4 blobtools/mapped.bam");
	system("blobtools create -i seq -b blobtools/mapped.bam -t blastx-out --db $nodeDB");
	system("rm seq");
	
	system("blobtools plot -i blobDB.json -r superkingdom -o superkingdom");
	system("mkdir blobtools_superkingdom");
	system("mv superkingdom* blobtools_superkingdom/");
	
	system("blobtools plot -i blobDB.json -r phylum -o phylum");
	system("mkdir blobtools_phylum");
	system("mv phylum* blobtools_phylum/");
	system("mv blobtools_phylum/*blobplot.bam0.png blobtools_phylum/Figure3.png");

	system("blobtools plot -i blobDB.json -r family -o family");
	system("mkdir blobtools_family");
	system("mv family* blobtools_family/");
	
	system("blobtools plot -i blobDB.json -r order -o order");
	system("mkdir blobtools_order");
	system("mv order* blobtools_order/");
	
	system("blobtools plot -i blobDB.json -r genus -o genus");
	system("mkdir blobtools_genus");
	system("mv genus* blobtools_genus/");
	
	system("blobtools plot -i blobDB.json -r species -o species");
	system("mkdir blobtools_species");
	system("mv species* blobtools_species/");

	system("mv blob* 4_contamineation_check/");

}

#==================================================================================================================
sub taxid {
	system("cut -f 2 blastx-out > ids");
	system("sleep 3s");
	system("taxonkit lineage -j 8 -t ids > lineage");
	system("sleep 3s");
	system("paste blastx-out lineage > blast-out-lineage");
	system("sleep 3s");
	open BLASTRESULT, "<blast-out-lineage" or die "cant open blastx-out file!\n";
	open STAT, ">contig_statistics" or die "cant write STAT file!\n";
	open INPUTMAP, "<mapping.stats" or die "cant open mapping\.stats file!\n";

	
	my $bb = 0;my @blastname = "";my @lineagename = "";my @blasttaxid = "";
	while (my $bline = <BLASTRESULT>) {
		chomp($bline);
		my @bbox = split(/\t/, $bline);
		$blastname[$bb] = $bbox[0];
		$lineagename[$bb] = $bbox[4];
		$blasttaxid[$bb] = $bbox[5];
		$bb++;
	}
	
	my $ix = 1;my @mapname = "";
	my $statsx = <INPUTMAP>;
	while (my $statsx = <INPUTMAP>) {
		chomp($statsx);
		my @boxx = split(/\t/, $statsx);
		$mapname[$i] = $boxx[0];#column0 name
		$ix++;
		my $ccc = 0;
		foreach my $var(@blastname){
			print STAT "$statsx\t$lineagename[$ccc]\t$blasttaxid[$ccc]\n" if($var eq $mapname[$i]);
			$ccc++;
		}
	}
	system("sleep 3s");
	system("cp blast-out-lineage mapping.stats");
	system("rm lineage ids");
}
